MLM: true
alpha: 0.9
batch_size: 64
batch_size_tta: 32
beta: 0.999
bias_lr_factor: 2.0
ckpt_dir: checkpoints/HAM_checkpoint/random100w_2HAMcaptions/best0.pth
cmt_depth: 4
dataset_name: RSTPReid
device: cuda
distributed: false
eval_period: 1
gamma: 0.1
id_loss_weight: 1.0
img_aug: true
img_size: !!python/tuple
- 384
- 128
k_sample_selection: 5
k_test: 128
k_tta: 4
local_rank: 0
log_period: 10
loss_names: sdm+id+mlm
lr: 5.0e-05
lr_factor: 5.0
lrscheduler: cosine
masked_token_rate: 0.8
masked_token_unchanged_rate: 0.1
milestones: !!python/tuple
- 20
- 50
mlm_loss_weight: 1.0
name: irra_rstp
neg_sample_range:
- 5
- 8
num_epoch: 60
num_instance: 4
num_workers: 8
optimizer: Adam
output_dir: output_rerun2/ham_rstp_tta/exp3/exp3.4.1/2025091511181
power: 0.9
pretrain_choice: ViT-B/16
resume: false
resume_ckpt_file: ''
root_dir: ./input/images
sample_selection: topk
sampler: random
stride_size: 16
target_lr: 0
temperature: 0.02
test_batch_size: 512
text_encoder_no_tta_layer:
- 0
- 6
text_length: 77
training: true
tta: true
uncertainty: abs_diff_log
uncertainty_coeffi: 0.001
uncertainty_i2t_temper: 1.0
uncertainty_t2i_temper: 1.0
uncertainty_temper: 1.0
uncertainty_temper_is_learnable: false
val_dataset: test
vocab_size: 49408
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0
